#build_docker_image:
#  image: docker:20
#  stage: build
#  services:
#    - docker:20-dind
#  script:
#    - cd ci/
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $CI_REGISTRY/striezel/morrowtools/ci-cross-win64:10.2-deb11 . -f Dockerfile_cross_win64
#    - docker push $CI_REGISTRY/striezel/morrowtools/ci-cross-win64:10.2-deb11
#    - docker logout $CI_REGISTRY
win64_cross:
  image: registry.gitlab.com/striezel/morrowtools/ci-cross-win64:10.2-deb11
  stage: build
  before_script:
    - apt-get update && apt-get -y upgrade
  script:
    # build
    - export CXX=x86_64-w64-mingw32-c++
    - export CC=x86_64-w64-mingw32-gcc
    - mkdir build
    - cd build
    - cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
    - make -j4
    # tests
    - ctest -V
    # Collect build artifacts in one place.
    - mkdir -p artifacts
    - cp mw/cell_translator/cell_translator.exe artifacts/
    - cp mw/data_cleaner/data_cleaner.exe artifacts/
    - cp mw/skill_rebalance/skill_rebalance.exe artifacts/
    - cp mw/spell_rename/spell_rename.exe artifacts/
    - cp sr/conv_cams/conv_cams.exe artifacts/
    - cp sr/formID_finder/formID_finder.exe artifacts/
    - cp sr/race_resize/race_resize.exe artifacts/
    # build artifacts
  artifacts:
    paths:
      - build/artifacts/

coverage:
  image: debian:11-slim
  stage: test
  before_script:
    - apt-get update && apt-get -y upgrade
    - apt-get install -y catch cmake g++-10 gcovr pkg-config zlib1g-dev
  script:
    # build
    - export CXX=g++-10
    - export CC=gcc-10
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCODE_COVERAGE=ON ../
    - make -j4
    # tests
    - ctest -V
    # collect code coverage data
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
#    - lcov -c --directory . --output-file main_coverage.info
#    - genhtml main_coverage.info --output-directory ../public
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      cobertura: build-coverage/coverage.xml
#    paths:
#      - public
