language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install zlib1g zlib1g-dev libboost-dev -y
script:
  - mkdir ./Build
  - cd ./Build
  - cmake ../
  - make
notifications:
  email: false
