/*
 -------------------------------------------------------------------------------
    This file is part of the Morrowind Tools Project.
    Copyright (C) 2023  Dirk Stolle

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 -------------------------------------------------------------------------------
*/

#include "DarkElfNamesPurge.hpp"

namespace MWTP
{

std::vector<std::string> DarkElfNamesPurge::purge()
{
  return {
    "angaredhel",
    "arantamo",
    "arnas therethi",
    "aundae vampire 1",
    "aundae vampire 5",
    "avon oran",
    "berne vampire 1",
    "berne vampire 3",
    "Black Dart Adren",
    "Black Dart Draren",
    "Black Dart Gilur",
    "Black Dart Malar",
    "Black Dart Urvyn",
    "bm_roguenecro1",
    "bm_roguenecro2",
    "bm_roguenecro3",
    "bm_smugglers_darkelf",
    "bm_smugglers_darkelf_f",
    "bm_werewolf_wild03",
    "brara morvayn",
    "brelda quintella",
    "buoyant armiger_wander",
    "cattle_bre_f01",
    "cattle_bre_m01",
    "cattle_dun_f01",
    "cattle_dun_m01",
    "Chappy_test_guy",
    "chargen name",
    "db_assassin1",
    "db_assassin1a",
    "db_assassin1b",
    "db_assassin1c",
    "db_assassin2",
    "db_assassin2a",
    "db_assassin3",
    "db_assassin3a",
    "db_assassin4",
    "db_assassin4a",
    "dead de female",
    "dead de female_01",
    "dead de male",
    "dead de male_01",
    "dead de male_berandas",
    "dead de male_tomb01",
    "dead de male_tomb02",
    "dead elite ord",
    "dead ordinator",
    "dead ordinator_key",
    "dead warlock",
    "drals indobar",
    "dreamer",
    "dreamer guard",
    "dreamer priest",
    "dreamer prophet",
    "dreamer worker",
    "dreamer_02",
    "dreamer_04",
    "dreamer_05",
    "dreamer_06",
    "dreamer_dead",
    "dreamer_f_01",
    "dreamer_f_key",
    "dreamer_ranged",
    "Dreamer_Talker",
    "Dreamer_Talker01",
    "Dreamer_Talker02",
    "Dreamer_Talker03",
    "Dreamer_Talker04",
    "Dreamer_Talker05",
    "Dreamer_Talker06",
    "Dreamer_Talker07",
    "Dreamer_Talker08",
    "Dreamer_Talker09",
    "Dreamer_Talker10",
    "Dreamer_Talker11",
    "Dreamer_Talker12",
    "edd theman",
    "feril salmyn",
    "Gee-Pop Varis",
    "ghost_npc_conoon chodal",
    "ghost_npc_hort_ledd",
    "ghost_npc_peakstar",
    "Goris the Maggot King",
    "grand inquisitor",
    "Granny Varis",
    "Guard_Helseth",
    "Guard_Helseth_attack",
    "Guard_HighOrd_Attack",
    "hetman abelmawia",
    "hlaalu guard",
    "hlaalu guard_outside",
    "hlaalu sharpshooter",
    "kind erushara",
    "King Hlaalu Helseth",
    "lauravenya",
    "mastrius",
    "miner_01",
    "miner_02",
    "miner_03",
    "miner_dead00",
    "miner_dead01",
    "Morty_dead",
    "nina",
    "oisig",
    "ordinator stationary",
    "ordinator wander",
    "ordinator wander_hp",
    "ordinator wander_ilpe_1",
    "ordinator wander_ilpe_2",
    "ordinator_bal_ur",
    "ordinator_high fane",
    "ordinator_MH_Sadri",
    "ordinator_mh_stationary",
    "ordinator_mh_TBasement",
    "ordinator_mh_TH_UNI",
    "ordinator_mournhold",
    "ordinator_wander_hvault",
    "ordinator_wander_tvault",
    "player",
    "quarra vampire 1",
    "quarra vampire 4",
    "redoran guard female",
    "redoran guard male",
    "redoran guard sarethi1",
    "redoran guard sarethi2",
    "redoran guard sarethi3",
    "redoran guard sarethi4",
    "redoran guard shooter",
    "redoran guard_Andasreth",
    "royal guard_karrod",
    "sadas mavandes",
    "Satyana",
    "savor hlan",
    "shashev",
    "stlennius vibato",
    "svadstar",
    "telvanni guard",
    "telvanni guard_stand",
    "telvanni sharpshooter",
    "todd",
    "vabbar dinadad",
    "Vedam Dren",
    "viras guls",
    "vonos veri",
    "widow vabdas",
    "yakin bael",
    "yeherradad"
  };
}

} // namespace
