# Note: This Dockerfile attempts to build the project by cross-compiling it
#       for 32-bit Windows OS via MinGW.

FROM debian:11-slim
LABEL maintainer="Dirk Stolle <striezel-dev@web.de>"
# Always update any existing packages first.
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y
# Install build toolchain.
RUN apt-get install -y catch cmake pkg-config \
    binutils-mingw-w64-i686 \
    g++-mingw-w64-i686-win32 \
    gcc-mingw-w64-i686-win32 \
    mingw-w64-i686-dev \
    libz-mingw-w64-dev
# Set environment variables.
ENV CXX=i686-w64-mingw32-c++
ENV CC=i686-w64-mingw32-gcc
# Prepare build directory and perform build.
RUN mkdir -p /opt/morrowtools
COPY ./ /opt/morrowtools
WORKDIR /opt/morrowtools
RUN mkdir build && cd build && cmake .. && make -j4 && ctest -V
# Collect artifacts and dependencies.
RUN mkdir -p /opt/morrowtools/build/artifacts && \
    cd /opt/morrowtools/build && \
    cp mw/cell_translator/cell_translator.exe artifacts/ && \
    cp mw/data_cleaner/data_cleaner.exe artifacts/ && \
    cp mw/skill_rebalance/skill_rebalance.exe artifacts/ && \
    cp mw/spell_rename/spell_rename.exe artifacts/ && \
    cp sr/bsa_cli/bsa-cli.exe artifacts/ && \
    cp sr/conv_cams/conv_cams.exe artifacts/ && \
    cp sr/formID_finder/formID_finder.exe artifacts/ && \
    cp sr/race_resize/race_resize.exe artifacts/ && \
    cp /usr/lib/gcc/i686-w64-mingw32/10-win32/libstdc++-6.dll artifacts/ && \
    cp /usr/i686-w64-mingw32/lib/zlib1.dll artifacts/
RUN apt-get install -y zip && \
    cd /opt/morrowtools/build && \
    zip artifacts.zip artifacts/*.exe artifacts/*.dll
