name: Clang

on: push

jobs:
  ubuntu_clang:
    strategy:
      matrix:
        version: [8, 9, 10]
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake clang-${{ matrix.version }} liblz4-dev pkg-config zlib1g-dev
      - name: Install LLVM C++ Standard Library
        run: |
          sudo apt-get install -y libc++-${{ matrix.version }}-dev
        if: matrix.version == 8
      - name: Syntax check
        run: |
          export CXX=clang++-${{ matrix.version }}
          ./ci/cpplint.sh
        if: matrix.version == 10
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build without LZ4 support on Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-no-lz4
          cd build-no-lz4
          cmake ../ -DAUTODETECT_LZ4=OFF -DDISABLE_LZ4=ON
          make -j2
        if: matrix.version == 9
      - name: Test build without LZ4 support
        run: |
          cd "$GITHUB_WORKSPACE"/build-no-lz4
          ctest -V
        if: matrix.version == 9

  clang10_lto_static:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake clang-10 liblz4-dev pkg-config zlib1g-dev
      - name: Build with Clang 10
        run: |
          export CXX=clang++-10
          export CC=clang-10
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
