name: MSYS2

on: push

jobs:
  msys2_mingw64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            mingw-w64-x86_64-catch
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-lz4
            mingw-w64-x86_64-make
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
      - name: Build
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: Tests
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked binaries
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          # Skyrim tools
          cmake --build . -j2 --target bsa-cli
          cmake --build . -j2 --target conv_cams
          cmake --build . -j2 --target formID_finder
          cmake --build . -j2 --target small_high_elves
          # Morrowind tools
          cmake --build . -j2 --target cell_translator
          cmake --build . -j2 --target data_cleaner
          cmake --build . -j2 --target skill_rebalance
          cmake --build . -j2 --target spell_rename
      - name: Collect statically linked artifacts
        run: |
          export MSYSTEM=MINGW64
          mkdir -p "$GITHUB_WORKSPACE"/artifacts
          cd "$GITHUB_WORKSPACE"
          cp build-static/mw/cell_translator/cell_translator.exe artifacts/
          cp build-static/mw/data_cleaner/data_cleaner.exe artifacts/
          cp build-static/mw/skill_rebalance/skill_rebalance.exe artifacts/
          cp build-static/mw/spell_rename/spell_rename.exe artifacts/
          cp build-static/sr/bsa_cli/bsa-cli.exe artifacts/
          cp build-static/sr/conv_cams/conv_cams.exe artifacts/
          cp build-static/sr/formID_finder/formID_finder.exe artifacts/
          cp build-static/sr/small_high_elves/small_high_elves.exe artifacts/
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: msys2-artifacts-static-linking
          path: |
            artifacts/*.exe
      - name: Collect files for bsa-cli
        run: |
          export MSYSTEM=MINGW64
          mkdir -p "$GITHUB_WORKSPACE"/bsa-cli
          cd "$GITHUB_WORKSPACE"
          cp build-static/sr/bsa_cli/bsa-cli.exe bsa-cli/
          cp sr/bsa_cli/readme.md bsa-cli/
          cp sr/bsa_cli/changelog.md bsa-cli/
          cp LICENSE bsa-cli/
      - name: Create bsa-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: bsa-cli-static-msys2
          path: |
            bsa-cli/*
      - name: Collect files for Form ID finder
        run: |
          export MSYSTEM=MINGW64
          mkdir -p "$GITHUB_WORKSPACE"/formID_finder
          cd "$GITHUB_WORKSPACE"
          cp build-static/sr/formID_finder/formID_finder.exe formID_finder/
          cp sr/formID_finder/readme.md formID_finder/
          cp sr/formID_finder/ChangeLog.de.md formID_finder/
          cp sr/formID_finder/ChangeLog.en.md formID_finder/
          cp LICENSE formID_finder/
      - name: Create Form ID finder artifact
        uses: actions/upload-artifact@v3
        with:
          name: formID-finder-static-msys2
          path: |
            formID_finder/*
