name: Sanitizers

on: push

jobs:
  sanitizer:
    runs-on: ubuntu-22.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake g++-12 libfuse3-dev liblz4-dev pkg-config zlib1g-dev
          sudo apt-get install -y libasan8 libubsan1
      - name: Build with GCC 12 and sanitizers enabled
        run: |
          export CXX=g++-12
          export CC=gcc-12
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../ -DENABLE_SANITIZER=ON
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
